[package]
name = "meow-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0"
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# wtransport retiré cause échec build environnement
